### ISSUE TITLE
Wow this is awesome! I do have a question

### ISSUE THREAD

**Issue by benzaote** [MaciejGrochowski93/fightmetric#1]
Hey, I saw the code you wrote for loading data about fighters in the Spring Boot application and I think it's really cool. I'm just curious about how the code determines which fighters to pull data for. Is there any way you could elaborate on that for me? I'm especially interested in knowing if there is a way to change the number of fighters that the code pulls data for. Thanks in advance for any insights you can provide!

**Comment by MaciejGrochowski93** [comment]
Hey benzaote, glad to hear your positive feedback.

> I'm just curious about how the code determines which fighters to pull data for.

I simply put the link to upcoming fights into the ReadingServiceImpl:
`private String mainURL = "http://www.ufcstats.com/statistics/events/upcoming";`
And only the events that didn't happen yet are getting analysed.

[Jsoup library](https://www.baeldung.com/java-with-jsoup) provides a Document, which allows you to scrap data from websites. I had to manually check which html blocks contain statistics I'm looking for (in this case "b-link b-link_style_black").

> I'm especially interested in knowing if there is a way to change the number of fighters that the code pulls data for.

If you ask literally about the amount of fighters, you could create another DataLoader's method:

```
    public List<FightSummary> getLimitedFightSummaryList(int fightersAmount) {
        if (fightersAmount <= fightSummaryList.size()) {
            return fightSummaryList.stream()
                    .limit(fightersAmount)
                    .collect(Collectors.toList());
        }
        return fightSummaryList;
    }
```

Then call this method from Controller, by adding a new endpoint with a @PathVariable int amount.

**Comment by benzaote** [comment]
That answered my question! thanks so much for taking the time to help me out! Great project thank you!
